repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff lint
        entry: uv run ruff check --fix
        language: system
        types: [python]
      - id: ruff-format
        name: ruff format
        entry: uv run ruff format
        language: system
        types: [python]
      - id: pyright
        name: pyright
        entry: uv run pyright
        language: system
        types: [python]
        pass_filenames: false

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: uv run pytest -m "not integration"
        language: system
        pass_filenames: false

    
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.9.21
    hooks:
      # Check uv lockfile is up to date
      - id: uv-lock
        name: Check uv lockfile
        files: pyproject.toml
        args: [--check]
